export const headers = [
  { key: 'cabinet', title: '№ кабинета' },
  { key: 'position', title: 'Должность' },
  { key: 'fullName', title: 'Ф.И.О.' },
  { key: 'internalPhone', title: 'Внутренний номер' },
  { key: 'cityPhone', title: 'Городской номер' },
  { key: 'mobilePhone', title: 'Сотовый номер' },
  { key: 'email', title: 'Почта' },
];
export const users = [
  {
    department: 'Руководство',
    cabinet: '101',
    position: 'Директор',
    fullName: 'Иванов Петр Сергеевич',
    internalPhone: '101',
    cityPhone: '+7 (495) 123-45-67',
    mobilePhone: '+7 (900) 123-45-67',
    email: 'ivanov@company.com',
  },
  {
    department: 'Руководство',
    cabinet: '102',
    position: 'Заместитель директора',
    fullName: 'Смирнова Ольга Владимировна',
    internalPhone: '102',
    cityPhone: '+7 (495) 123-45-68',
    mobilePhone: '+7 (900) 123-45-68',
    email: 'smirnova@company.com',
  },
  {
    department: 'Отдел продаж',
    cabinet: '201',
    position: 'Менеджер по продажам',
    fullName: 'Петров Алексей Дмитриевич',
    internalPhone: '201',
    cityPhone: '+7 (495) 123-45-69',
    mobilePhone: '+7 (900) 123-45-69',
    email: 'petrov@company.com',
  },
  {
    department: 'Отдел продаж',
    cabinet: '202',
    position: 'Старший менеджер',
    fullName: 'Кузнецова Екатерина Игоревна',
    internalPhone: '202',
    cityPhone: '+7 (495) 123-45-70',
    mobilePhone: '+7 (900) 123-45-70',
    email: 'kuznetsova@company.com',
  },
  {
    department: 'Бухгалтерия',
    cabinet: '103',
    position: 'Главный бухгалтер',
    fullName: 'Васильева Мария Петровна',
    internalPhone: '103',
    cityPhone: '+7 (495) 123-45-71',
    mobilePhone: '+7 (900) 123-45-71',
    email: 'vasileva@company.com',
  },
  {
    department: 'Бухгалтерия',
    cabinet: '203',
    position: 'Бухгалтер',
    fullName: 'Николаев Денис Олегович',
    internalPhone: '203',
    cityPhone: '+7 (495) 123-45-72',
    mobilePhone: '+7 (900) 123-45-72',
    email: 'nikolaev@company.com',
  },
  {
    department: 'IT-отдел',
    cabinet: '301',
    position: 'IT-специалист',
    fullName: 'Федоров Артем Валерьевич',
    internalPhone: '301',
    cityPhone: '+7 (495) 123-45-73',
    mobilePhone: '+7 (900) 123-45-73',
    email: 'fedorov@company.com',
  },
  {
    department: 'IT-отдел',
    cabinet: '302',
    position: 'Системный администратор',
    fullName: 'Орлова Наталья Сергеевна',
    internalPhone: '302',
    cityPhone: '+7 (495) 123-45-74',
    mobilePhone: '+7 (900) 123-45-74',
    email: 'orlova@company.com',
  },
  {
    department: 'Юридический отдел',
    cabinet: '401',
    position: 'Юрист',
    fullName: 'Белов Константин Александрович',
    internalPhone: '401',
    cityPhone: '+7 (495) 123-45-75',
    mobilePhone: '+7 (900) 123-45-75',
    email: 'belov@company.com',
  },
  {
    department: 'HR-отдел',
    cabinet: '402',
    position: 'HR-менеджер',
    fullName: 'Григорьева Анна Викторовна',
    internalPhone: '402',
    cityPhone: '+7 (495) 123-45-76',
    mobilePhone: '+7 (900) 123-45-76',
    email: 'grigorieva@company.com',
  },
  {
    department: 'Маркетинг',
    cabinet: '501',
    position: 'Маркетолог',
    fullName: 'Тихонов Иван Павлович',
    internalPhone: '501',
    cityPhone: '+7 (495) 123-45-77',
    mobilePhone: '+7 (900) 123-45-77',
    email: 'tikhonov@company.com',
  },
  {
    department: 'Аналитический отдел',
    cabinet: '502',
    position: 'Аналитик',
    fullName: 'Зайцева Юлия Дмитриевна',
    internalPhone: '502',
    cityPhone: '+7 (495) 123-45-78',
    mobilePhone: '+7 (900) 123-45-78',
    email: 'zaitseva@company.com',
  },
  {
    department: 'Администрация',
    cabinet: '601',
    position: 'Секретарь',
    fullName: 'Крылов Михаил Игоревич',
    internalPhone: '601',
    cityPhone: '+7 (495) 123-45-79',
    mobilePhone: '+7 (900) 123-45-79',
    email: 'krylov@company.com',
  },
  {
    department: 'Администрация',
    cabinet: '602',
    position: 'Офис-менеджер',
    fullName: 'Соколова Виктория Андреевна',
    internalPhone: '602',
    cityPhone: '+7 (495) 123-45-80',
    mobilePhone: '+7 (900) 123-45-80',
    email: 'sokolova@company.com',
  },
  {
    department: 'Технический отдел',
    cabinet: '701',
    position: 'Инженер',
    fullName: 'Павлов Сергей Николаевич',
    internalPhone: '701',
    cityPhone: '+7 (495) 123-45-81',
    mobilePhone: '+7 (900) 123-45-81',
    email: 'pavlov@company.com',
  },
  {
    department: 'Технический отдел',
    cabinet: '702',
    position: 'Технический специалист',
    fullName: 'Воробьева Татьяна Олеговна',
    internalPhone: '702',
    cityPhone: '+7 (495) 123-45-82',
    mobilePhone: '+7 (900) 123-45-82',
    email: 'vorobeva@company.com',
  },
  {
    department: 'Логистика',
    cabinet: '801',
    position: 'Логист',
    fullName: 'Лебедев Андрей Владимирович',
    internalPhone: '801',
    cityPhone: '+7 (495) 123-45-83',
    mobilePhone: '+7 (900) 123-45-83',
    email: 'lebedev@company.com',
  },
  {
    department: 'Снабжение',
    cabinet: '802',
    position: 'Снабженец',
    fullName: 'Егорова Ирина Борисовна',
    internalPhone: '802',
    cityPhone: '+7 (495) 123-45-84',
    mobilePhone: '+7 (900) 123-45-84',
    email: 'egorova@company.com',
  },
  {
    department: 'Архив',
    cabinet: '901',
    position: 'Архивариус',
    fullName: 'Степанов Дмитрий Петрович',
    internalPhone: '901',
    cityPhone: '+7 (495) 123-45-85',
    mobilePhone: '+7 (900) 123-45-85',
    email: 'stepanov@company.com',
  },
  {
    department: 'Курьерская служба',
    cabinet: '902',
    position: 'Курьер',
    fullName: 'Козлова Елена Алексеевна',
    internalPhone: '902',
    cityPhone: '+7 (495) 123-45-86',
    mobilePhone: '+7 (900) 123-45-86',
    email: 'kozlovа@company.com',
  },
];

//Создаю новый массив, фильтрую пользователей по отделам
export const getDepartments = () => {
  const arrayOriginalDepartments = Array.from(
    new Set(users.map((user) => user.department)),
  );
  const departmentsArr = arrayOriginalDepartments.map((departmentName) => ({
    name: departmentName,
    users: users.filter((user) => user.department === departmentName),
  }));
  return departmentsArr;
};
